menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/xjiajiahao
    About: /about/

favicon: /favicon.png
#logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: xjiajiahao
duoshuo:

# Analytics
# google-analytics:
ga: UA-67050035-1

# Copyright Infomation
startyear: 2015

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: true
