menu:
    Stephen Tse's Blog: /
    Archive: /archives/
    GitHub: https://github.com/xjiajiahao
    About: /about/

favicon: /favicon.png
#logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: xjiajiahao
duoshuo:

# Analytics
# google-analytics:
ga: UA-67050035-1

# Copyright Infomation
startyear: 2015
